ProyectoPP/ProyectoPP/Models/sprint.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sprint()
        {
            this.historiasDeUsuario = new HashSet<historiasDeUsuario>();
        }
    
        public string id { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public string proyectoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiasDeUsuario> historiasDeUsuario { get; set; }
        public virtual proyecto proyecto { get; set; }
    }
}

ProyectoPP/ProyectoPP/Controllers/sprintsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoPP.Models;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace ProyectoPP.Controllers
{
    public class sprintsController : Controller
    {
        private patopurificEntitiesGeneral db = new patopurificEntitiesGeneral();

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private async Task<bool> revisarPermisos(string permiso)
        {

            string userName = System.Web.HttpContext.Current.User.Identity.Name;
            var user = UserManager.FindByName(userName);
            var rol = user.Roles.SingleOrDefault().RoleId;

            var permisoID = db.permisos.Where(m => m.permiso == permiso).First().id_permiso;
            var listaRoles = db.AspNetRoles.Where(m => m.permisos.Any(c => c.id_permiso == permisoID)).ToList().Select(n => n.Id);

            bool userRol = false;
            foreach (var element in listaRoles)
            {
                if (element == rol)
                    userRol = true;
            }
            return userRol;
        }

        // GET: sprints
        public ActionResult Index()
        {

            Sprint2 modelo = new Sprint2();

            if ( !System.Web.HttpContext.Current.User.IsInRole("Estudiante")) // Si el usuario no es estudiante
            {

                // Seleccion para el dropdown de proyectos. Carga todos los proyectos que hay
                ViewBag.Proyecto = new SelectList(db.proyecto, "id", "nombre", "Seleccione un Proyecto");
            }

            else
            {
                var idproyecto = db.persona.Where(m => m.cedula == System.Web.HttpContext.Current.User.Identity.Name).First().IdProyecto;                

                // Seleccion para el dropdown de proyectos. Carga solo el proyecto donde participa el estudiante
                ViewBag.Proyecto = new SelectList(db.proyecto.Where(x => x.id == idproyecto), "id", "nombre");
                ViewBag.NombreProyecto = db.proyecto.Where(m => m.id == idproyecto).First().nombre;

            }
            return View(modelo);
        }

        public ActionResult SprintPlanning()
        {

            DatosSprintPlanning modelo = new DatosSprintPlanning();

            if (!System.Web.HttpContext.Current.User.IsInRole("Estudiante")) // Si el usuario no es estudiante
            {

                // Seleccion para el dropdown de proyectos. Carga todos los proyectos que hay
                ViewBag.Proyecto = new SelectList(db.proyecto, "id", "nombre");

                // El dropdown de sprints queda en blanco porque no sabemos aún cuál proyecto se va a seleccionar. Para esto solamente busco los sprints donde el id es igual ""
                ViewBag.Sprint = new SelectList(db.sprint.Where(x => x.proyectoId == ""), "id", "id");
                
                // Repito el proceso con las HU, busco las que tengan ID ""
                ViewBag.HU = db.historiasDeUsuario.Where(x => x.proyectoId == "").ToList();
               
            }

            else
            {
                var idproyecto = db.persona.Where(m => m.cedula == System.Web.HttpContext.Current.User.Identity.Name).First().IdProyecto;
                
                // Seleccion para el dropdown de proyectos. Carga solo el proyecto donde participa el estudiante
                ViewBag.Proyecto = new SelectList(db.proyecto.Where(x => x.id == idproyecto), "id", "nombre");

                // Seleccion para el dropdown de sprints. Carga todos los sprints que hay asociados al proyecto seleccionado
                ViewBag.Sprint = new SelectList(db.sprint.Where(x => x.proyectoId == idproyecto), "id", "id");

                // Lss hitorias de usuario no se cargan ya que necesito seleccionar un sprint
                ViewBag.HU = db.historiasDeUsuario.Where(x => x.proyectoId == "").ToList();

            }
            modelo.fechaC = db.fechas.ToList();
            return View(modelo);
        }

        // GET: sprints/Details/5
        public ActionResult Details(string id, string proyectoId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sprint sprint = db.sprint.Find(id, proyectoId);
            Sprint2 s = new Sprint2();
            s.fechaInicio = sprint.fechaInicio;


            /*string[] fecha = sprint.fechaFinal.ToString().Split('/');
            int año = Int32.Parse(fecha[2]);

            s.fechaFinal = new DateTime(Int32.Parse(fecha[2]), Int32.Parse(fecha[1]), Int32.Parse(fecha[1])  ); */
            s.fechaFinal = sprint.fechaFinal;          
            s.id = sprint.id;
            s.proyectoId = sprint.proyectoId;

            ViewBag.nombreProyecto = db.proyecto.Where(p => p.id == proyectoId).FirstOrDefault().nombre;

            if (sprint == null)
            {
                return HttpNotFound();
            }
            return View(s);
        }

        // GET: sprints/Create
        
        public ActionResult Create(string proyectoId)
        {
            if (proyectoId != null)
            {

                ViewBag.nombreProyecto = db.proyecto.Where(p => p.id == proyectoId).First().nombre;

                //autogenero el numero de sprint
                var max = db.sprint.Where(s => s.proyectoId == proyectoId).Max(s => s.id);
                if (max == null) max = "0";
                int n = Int32.Parse(max);
                n = n + 1;

                //asigno valores que ya deben de ir por defecto y no se pueden modificar
                ViewBag.proyectoId = proyectoId;
                ViewBag.id = "" + n;
                
                Sprint2 mod = new Sprint2();
                mod.proyectoId = proyectoId;
                mod.nombreProyecto = db.proyecto.Where(p => p.id == proyectoId).First().nombre;
                mod.id = "" + n;


                return View(mod);
            }
            TempData["msg"] = "<script>alert('Primero seleccione un pryecto');</script>";
            return RedirectToAction("Index");
        }

        // POST: sprints/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Sprint2 sprint)
        {
            sprint nuevoSprint = new sprint();
            //nuevoSprint.historiasDeUsuario = sprint.historiasDeUsuario;
            nuevoSprint.id = sprint.id;
            nuevoSprint.fechaInicio = sprint.fechaInicio;
            nuevoSprint.fechaFinal = sprint.fechaFinal;
            nuevoSprint.proyectoId = sprint.proyectoId;
            nuevoSprint.proyecto = sprint.proyecto;
            db.sprint.Add(nuevoSprint);
                try
                {
                    

                    
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    TempData["msg"] = "<script>alert('Ha ocurrido un error al crear el sprint');</script>";

                    return View(sprint);
                }

            //ViewBag.proyectoId = new SelectList(db.proyecto, "id", "nombre", sprint.proyectoId);
            //return View(sprint);
        }

        public ActionResult CreateHito()
        {
            return View();

            TempData["msg"] = "<script>alert('Primero seleccione un pryecto');</script>";
            return RedirectToAction("Index");
        }

        // POST: sprints/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateHito(fechas fecha)
        {
            //sprint nuevoSprint = new sprint();
            //nuevoSprint.historiasDeUsuario = sprint.historiasDeUsuario;
            //nuevoSprint.id = sprint.id;
            //nuevoSprint.fechaInicio = sprint.fechaInicio;
            //nuevoSprint.fechaFinal = sprint.fechaFinal;
            //nuevoSprint.proyectoId = sprint.proyectoId;
            //nuevoSprint.proyecto = sprint.proyecto;
            db.fechas.Add(fecha);
            try
            {
                db.SaveChanges();
                return RedirectToAction("SprintPlanning");
            }

            catch (Exception ex)
            {
                Console.WriteLine(ex);
                TempData["msg"] = "<script>alert('Ha ocurrido un error al crear el sprint');</script>";

                return View();
            }

            //ViewBag.proyectoId = new SelectList(db.proyecto, "id", "nombre", sprint.proyectoId);
            //return View(sprint);
        }

        // GET: sprints/Edit/5
        public ActionResult Edit(string id, string proyectoId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // se busca en la base de datos el sprinta editar
            sprint sprintTMP = db.sprint.Find(id, proyectoId);
            Sprint2 sprint = new Sprint2();

            // en caso de que no lo encuentre
            if (sprintTMP == null)
            {
                return HttpNotFound();

ProyectoPP/ProyectoPP/Views/sprints/Create.cshtml
@model ProyectoPP.Models.Sprint2
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Sprint</h2>

@section Scripts {
    <!--Todo esto es para el date picker-->
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">

    <script type="text/javascript">

                             $(document).ready(function () {
                                 $('input[type=datetime]').datepicker({
                                     dateFormat: "yy-mm-dd",
                                     changeMonth: true,
                                     changeYear: true,
                                     yearRange: "-60:+0"
                                 });

                             });
    </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.Label("Sprint", htmlAttributes: new { @class = "control-label col-md-2" })

            @Html.HiddenFor(m => Model.id)
            @Html.HiddenFor(m => Model.proyecto)
            @Html.HiddenFor(m => Model.proyectoId)

            <div class="col-md-10">
                <input type="text" name="pass" value=@(Model.id) disabled><br><br />
            </div>
        </div>

            <div class="form-group">
                <br>@Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
                    <br />
                </div>
            </div>


            <br>
            <div class="form-group">
                @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger" })
                    <br /><br />
                </div>
            </div>



            <br>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Aceptar" class="btn btn-default" />
                    <button class="btn btn-default" onclick="location.href='@Url.Action("Create", "sprints",new { id = Model.id, proyectoId = Model.proyectoId  } )';return false;">Cancelar</button>
                </div>
            </div>
        </div>
}

ProyectoPP/ProyectoPP/Views/sprints/CreateHito.cshtml
@model ProyectoPP.Models.fechas

<h2>Crear Hitos</h2>

@section Scripts {
    <!--Todo esto es para el date picker-->
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">

    <script type="text/javascript">

                             $(document).ready(function () {
                                 $('input[type=datetime]').datepicker({
                                     dateFormat: "yy-mm-dd",
                                     changeMonth: true,
                                     changeYear: true,
                                     yearRange: "-60:+0"
                                 });

                             });
    </script>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fechaCorte, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaCorte, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaCorte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="CreateHito" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ProyectoPP/ProyectoPP/Views/sprints/Delete.cshtml
@model ProyectoPP.Models.sprint

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Sprint</h2>

<h3>¿Desea eliminar este sprint?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.proyecto.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.proyecto.nombre)<br><br>
        </dd>


        <dt>
            <label>Fecha de inicio</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaInicio)<br><br>
        </dd>



        <dt>
            <label>Fecha de final</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaFinal)<br><br><br>
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Aceptar" class="btn btn-default" />
            <button class="btn btn-default" onclick="location.href='@Url.Action("Details", "sprints", new { id = Model.id, proyectoId = Model.proyectoId  })';return false;">Cancelar</button> 
            
        </div>
    }
</div>

ProyectoPP/ProyectoPP/Views/sprints/Details.cshtml
@model ProyectoPP.Models.Sprint2

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles de sprint</h2>

<div>
    <h4>Sprint  @Model.id</h4>
    <hr />


    <div class="form-group">
        <div class="col-md-offset-6 col-md-10">
            <!--Estos botones funcionan como los action links. Solo que el orden de los parametros es un poco distinto en el orden-->
            <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "sprints", new { id = Model.id, proyectoId  = Model.proyectoId })'">Editar</button>
            
            <button class="btn btn-default" onclick="location.href='@Url.Action("Delete", "sprints", new { id = Model.id, proyectoId = Model.proyectoId  })'">Eliminar</button>
               

        </div>
    </div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.proyecto.nombre)
        </dt>

        <dd>
            <text>@ViewBag.nombreProyecto</text>
            @Html.DisplayFor(model => model.proyecto.nombre)<br><br>
        </dd>




        <br />
        <dt>
            @Html.DisplayNameFor(model => model.fechaInicio)
        </dt>
        <dd>
            <text>@Model.fechaInicio.ToShortDateString()</text><br><br>
        </dd>



        <br />
        <dt>
            @Html.DisplayNameFor(model => model.fechaFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaFinal)<br><br>
        </dd>

        

    </dl>
</div>

ProyectoPP/ProyectoPP/Views/sprints/Edit.cshtml
@model ProyectoPP.Models.Sprint2

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Sprint</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sprint @Model.id</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
                <br /><br />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger" })<br /><br />
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-default" />
                <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "sprints",new { id = Model.id, proyectoId = Model.proyectoId   })';return false;">Cancelar</button>
            </div>
        </div>


    </div>
}




@section Scripts {
    <!--Todo esto es para el date picker-->
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">

    <script type="text/javascript">

                             $(document).ready(function () {
                                 $('input[type=datetime]').datepicker({
                                     dateFormat: "yy-mm-dd",
                                     changeMonth: true,
                                     changeYear: true,
                                     yearRange: "-60:+0"
                                 });

                             });
    </script>
}

ProyectoPP/ProyectoPP/Views/sprints/Index.cshtml
@model ProyectoPP.Models.Sprint2
@using ProyectoPP.Models
@{
    ViewBag.Title = "SprintPlanning";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Administrar Sprints</h2>

<div class="form-group">
    <h4>Nombre del proyecto</h4>
    @if (true)
    {
        string resp = Html.Action("EsEstudiante", "Roles").ToString();
        if (resp == "1")
        {
            <h4>@ViewBag.NombreProyecto</h4>
            //<button class="btn btn-default col-md-offset-10" onclick="location.href='@Url.Action("Create", "sprints")'">Nuevo Sprint</button>            
        }
        else
        {
            <button class="btn btn-default col-md-offset-10" onclick="location.href='@Url.Action("Create", "sprints", new {proyectoId = Model.proyectoId  } )'">Insertar Sprint</button>
            
        }

    }

</div>

@using (Html.BeginForm("Actualizar", "sprints", FormMethod.Post, new { id = "sprintForm" }))
{
    @Html.AntiForgeryToken()


    string resp = Html.Action("EsEstudiante", "Roles").ToString();
    // pregunta si no es estudiante
    if (resp != "1")
    {
        <div class="col-md-3">
            @Html.DropDownListFor(m => m.proyectoId , (SelectList)ViewBag.Proyecto, "", htmlAttributes: new { @class = "form-control col-md-0", onchange = "$(\"#sprintForm\").submit()" })
            @Html.ValidationMessageFor(model => model.proyectoId, "", new { @class = "text-danger" })

        </div>
        
    }
}
<br /><br /><br />

<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.id )
        </th>

        <th>
            @Html.DisplayNameFor(model => model.fechaInicio  )
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaFinal)
        </th>
       
        <th></th>
    </tr>
    @if (ViewBag.Sprints!= null)
    {
        foreach (var item in (List<sprint>)ViewBag.Sprints)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.id)
                </td>

                <td>
                    <text>@item.fechaInicio.ToShortDateString()</text>
                </td>
                <td>
                    <text>@item.fechaFinal.ToString()</text>
                </td>

                <td>
                    @Html.ActionLink("Detalles", "Details", "sprints", new { id = item.id, proyectoId = item.proyectoId }, null)
                </td>
            </tr>
        }
    }
    
    

</table>

ProyectoPP/ProyectoPP/Views/sprints/SprintPlanning.cshtml
@using ProyectoPP.Models
@model ProyectoPP.Models.DatosSprintPlanning

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sprint Planning</h2>
<br><br>

@using (Html.BeginForm("ActualizarSprintPlanning", "sprints", FormMethod.Post, new { id = "SPForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">

        @Html.Label("Proyecto", htmlAttributes: new { @class = "control-label col-md-1" })

        @Html.DropDownListFor(m => m.ProyectoId, (SelectList)ViewBag.Proyecto, "", htmlAttributes: new { @class = "form-control col-md-2", onchange = "$(\"#SPForm\").submit()" })
        @Html.ValidationMessageFor(model => model.ProyectoId, "", new { @class = "text-danger" })

        @Html.Label("Sprint", htmlAttributes: new { @class = "control-label col-md-1 col-md-offset-3" })

        @Html.DropDownListFor(m => m.SprintID, (SelectList)ViewBag.Sprint, "", htmlAttributes: new { @class = "form-control col-md-1", onchange = "$(\"#SPForm\").submit()" })
        @Html.ValidationMessageFor(model => model.SprintID, "", new { @class = "text-danger" })

    </div>
}

<br><br><br><br>

<table class="table">
    <tr>

        <th>
            ID
        </th>

        <th>
            Alias
        </th>

        <th>
            Resultado
        </th>
        
        <th>
            Prioridad
        </th>
        
        <th>
            Estimación
        </th>
             
    </tr>

    @foreach (var item in (List<historiasDeUsuario>)ViewBag.HU)
    {
        <tr>
            <th>
                @Html.Raw(item.id)
            </th>

            <th>
                @Html.Raw(item.funcionalidad)
            </th>

            <th>
                @Html.Raw(item.resultado)
            </th>

            <th>
                @Html.Raw(item.prioridad)
            </th>

            <th>
                @Html.Raw(item.estimacion)
            </th>

            <td>
                @Html.ActionLink("Planificar", "Index", "tareas", new { HU = item.id }, null)
            </td>
        </tr>
    }

</table>

<br>
<h2>Hitos</h2>
<br>

@using (Html.BeginForm())
{
    <div class="form-group">
        <div class="col-md-offset-10 col-md-10">
            <!--Estos botones funcionan como los action links. Solo que el orden de los parametros es un poco distinto en el orden-->
            <button class="btn btn-default" onclick="location.href='@Url.Action("CreateHito", "sprints")'">Agregar Fecha</button>
            <br>
            <br>
        </div>
    </div>
}
<table class="table">

    <tr>
        <th>
            Fecha
        </th>
    </tr>

    @foreach (var item in Model.fechaC)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.fechaCorte)
            </td>
        </tr>
    }


</table>