ProyectoPP/ProyectoPP/Models/tarea.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarea()
        {
            this.progreso = new HashSet<progreso>();
            this.persona = new HashSet<persona>();
        }
    
        public string HU { get; set; }
        public int id { get; set; }
        public string nombre { get; set; }
        public int esfuerzo { get; set; }
    
        public virtual historiasDeUsuario historiasDeUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<progreso> progreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<persona> persona { get; set; }
    }
}

ProyectoPP/ProyectoPP/Controllers/tareasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoPP.Models;

namespace ProyectoPP.Controllers
{
    public class tareasController : Controller
    {
        private patopurificEntitiesGeneral db = new patopurificEntitiesGeneral();

        // GET: tareas
        public ActionResult Index(string HU)
        {
            var tarea = db.tarea.Where(t => t.HU == HU);
            ViewBag.HUid = HU;
            return View(tarea.ToList());
        }

        // GET: tareas/Details/5
        public ActionResult Details(string HU, int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tarea tarea = db.tarea.Find(HU, id);
            tarea.progreso = db.progreso.Where(t => t.HU == HU && t.id == id).ToList();
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // GET: tareas/Create
        public ActionResult Create(string HU)
        {
            ViewBag.HU = new SelectList(db.historiasDeUsuario, "id", "rol");
            tarea tarea = new tarea();
            tarea.HU = HU;
            return View(tarea);
        }

        // POST: tareas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tarea tarea)
        {
            if (ModelState.IsValid)
            {
                db.tarea.Add(tarea);
                db.SaveChanges();
                return RedirectToAction("Index", new { HU = tarea.HU });
            }

            ViewBag.HU = new SelectList(db.historiasDeUsuario, "id", "rol", tarea.HU);

            return View();
        }

        public ActionResult addProgreso(string HU, int id)
        {
            ViewBag.HU = new SelectList(db.historiasDeUsuario, "id", "rol");
            progreso progreso = new progreso();
            progreso.HU = HU;
            progreso.id = id;
            ViewBag.fechaCorte = new SelectList(db.fechas, "fechaCorte");
            return View(progreso);
        }

        // POST: tareas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addProgreso(progreso progreso)
        {
            if (ModelState.IsValid)
            {
                db.progreso.Add(progreso);
                db.SaveChanges();
                return RedirectToAction("Index", new { HU = progreso.HU });
            }

            ViewBag.HU = new SelectList(db.historiasDeUsuario, "id", "rol", progreso.HU);

            return View();
        }

        // GET: tareas/Edit/5
        public ActionResult Edit(string HU, int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tarea tarea = db.tarea.Find(HU, id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            ViewBag.HU = new SelectList(db.historiasDeUsuario, "id", "rol", tarea.HU);
            return View(tarea);
        }

        // POST: tareas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(tarea tarea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tarea).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { HU = tarea.HU });
            }
            ViewBag.HU = new SelectList(db.historiasDeUsuario, "id", "rol", tarea.HU);
            return View(tarea);
        }

        // GET: tareas/Delete/5
        public ActionResult Delete(string HU, int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tarea tarea = db.tarea.Find(HU, id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // POST: tareas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string HU, int id)
        {
            tarea tarea = db.tarea.Find(HU, id);
            db.tarea.Remove(tarea);
            db.SaveChanges();
            return RedirectToAction("Index", new { HU = tarea.HU });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoPP/ProyectoPP/Views/tareas/Create.cshtml
@model ProyectoPP.Models.tarea

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tareas HU: @Model.HU</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.esfuerzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.esfuerzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.esfuerzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoPP/ProyectoPP/Views/tareas/Delete.cshtml
@model ProyectoPP.Models.tarea

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body bgcolor="FFFFFF">
    <h2>Eliminar</h2>

    <h3>¿Está seguro que desea eliminar esta tarea?</h3>

    <div>

        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.nombre)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.nombre)
            </dd>

            <br />

            <dt>
                @Html.DisplayNameFor(model => model.esfuerzo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.esfuerzo)
            </dd>

            <br />

            <dt>
                @Html.DisplayNameFor(model => model.historiasDeUsuario.id)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.historiasDeUsuario.id)
            </dd>

            <br />

        </dl>

        <!--Cada método que devuelva algo para un método post del controlador, tiene que llevar un begin form-->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-offset-1 col-md-10">
                    <input type="submit" value="Aceptar" class="btn btn-default" />
                    <button class="btn btn-default" onclick="location.href='@Url.Action("Details", "tareas", new { HU = Model.HU, id = Model.id })';return false;">Cancelar</button>
                </div>
            </div>
        }

        <br /><br />

    </div>

</body>

ProyectoPP/ProyectoPP/Views/tareas/Details.cshtml
@model ProyectoPP.Models.tarea

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles de Tarea</h2>

<div>
    <div class="form-group">
        <div class="col-md-offset-6 col-md-10">
            <!--Estos botones funcionan como los action links. Solo que el orden de los parametros es un poco distinto en el orden-->
            <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "tareas", new { HU = Model.HU, id = Model.id })'">Editar</button>
            
            <button class="btn btn-default" onclick="location.href='@Url.Action("Delete", "tareas", new { HU = Model.HU, id = Model.id })'">Eliminar</button>

        </div>
    </div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <br />

        <dt>
            @Html.DisplayNameFor(model => model.esfuerzo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.esfuerzo)
        </dd>

        <br />

        <dt>
            @Html.DisplayNameFor(model => model.historiasDeUsuario.id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.historiasDeUsuario.id)
        </dd>

        <br />
        
    </dl>
</div>

<br>
<h2>Progreso</h2>
<br>

<div class="form-group">
    <div class="col-md-offset-10 col-md-10">
        <!--Estos botones funcionan como los action links. Solo que el orden de los parametros es un poco distinto en el orden-->
        <button class="btn btn-default" onclick="location.href='@Url.Action("addProgreso", "tareas", new { HU = Model.HU, id = Model.id })'">Agregar Progreso</button>
        <br>
        <br>
    </div>
</div>

<table class="table">

    <tr>
        <th>
            Fecha
        </th>

        <th>
            Progreso
        </th>
    </tr>

    @foreach (var item in Model.progreso)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.fechaCorte)
            </td>

            <td>
                @Html.DisplayFor(model => item.porcentaje)
            </td>
        </tr>
    }


</table>

ProyectoPP/ProyectoPP/Views/tareas/Edit.cshtml
@model ProyectoPP.Models.tarea

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Tareas</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tarea</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HU)

        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.esfuerzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.esfuerzo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.esfuerzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-default" />
                <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "tareas", new { HU = Model.HU, id = Model.id })';return false;">Cancelar</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoPP/ProyectoPP/Views/tareas/Index.cshtml
@model IEnumerable<ProyectoPP.Models.tarea>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Tareas HU: @ViewBag.HUid</h2>

<div class="form-group">
    <div class="col-md-offset-10 col-md-10">
        <!--Estos botones funcionan como los action links. Solo que el orden de los parametros es un poco distinto en el orden-->
        <button class="btn btn-default" onclick="location.href='@Url.Action("Create", "tareas", new { HU = @ViewBag.HUid })'">Insertar Tarea</button>
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.esfuerzo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.esfuerzo)
        </td>
        <td>
            @Html.ActionLink("Detalles", "Details", new { HU = item.HU, id = item.id }) 
        </td>
    </tr>
}

</table>

ProyectoPP/ProyectoPP/Views/tareas/addProgreso.cshtml
@model ProyectoPP.Models.progreso

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>progreso</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.fechaCorte, "fechaCorte", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fechaCorte", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fechaCorte, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.porcentaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.porcentaje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.porcentaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="addProgreso" class="btn btn-default" />
            </div>
        </div>
    </div>
}