ProyectoPP/ProyectoPP/Models/Documentacion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentacion
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
        public string HUid { get; set; }
    
        public virtual historiasDeUsuario historiasDeUsuario { get; set; }
    }
}

ProyectoPP/ProyectoPP/Controllers/DocumentacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.IO;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;

namespace ProyectoPP.Controllers
{
    public class DocumentacionController : Controller
    {
        private ProyectoPP.Models.patopurificEntitiesGeneral db = new ProyectoPP.Models.patopurificEntitiesGeneral();

        // GET: Documentacion
        public ActionResult Index()
        {
            return View(GetFiles());
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase postedFile)
        {
            var docId = db.Documentacion.Count();

            docId++;
            
            byte[] bytes;
            using (BinaryReader br = new BinaryReader(postedFile.InputStream))
            {
                bytes = br.ReadBytes(postedFile.ContentLength);
            }
            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "INSERT INTO Documentacion VALUES (@id, @nombre, @ContentType, @Data)";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    cmd.Parameters.AddWithValue("@id", docId);
                    cmd.Parameters.AddWithValue("@nombre", Path.GetFileName(postedFile.FileName));
                    cmd.Parameters.AddWithValue("@ContentType", postedFile.ContentType);
                    cmd.Parameters.AddWithValue("@Data", bytes);
                    con.Open();
                    cmd.ExecuteNonQuery();
                    con.Close();
                }
            }

            return View(GetFiles());
        }

        [HttpPost]
        public ActionResult DownloadFile(int? fileId)
        {
            byte[] bytes;
            string fileName, contentType;
            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.CommandText = "SELECT nombre, Data, ContentType FROM Documentacion WHERE id=@Id";
                    cmd.Parameters.AddWithValue("@Id", fileId);
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        sdr.Read();
                        bytes = (byte[])sdr["Data"];
                        contentType = sdr["ContentType"].ToString();
                        fileName = sdr["nombre"].ToString();
                    }
                    con.Close();
                }
            }

            return File(bytes, contentType, fileName);
        }

        private static List<ProyectoPP.Models.DocumentacionModel> GetFiles()
        {
            List<ProyectoPP.Models.DocumentacionModel> files = new List<ProyectoPP.Models.DocumentacionModel>();
            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand("SELECT id, nombre FROM Documentacion"))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            files.Add(new Models.DocumentacionModel
                            {
                                Id = Convert.ToInt32(sdr["id"]),
                                Nombre = sdr["nombre"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }
            return files;
        }
    }
}

ProyectoPP/ProyectoPP/Views/Documentacion/Index.cshtml
@model IEnumerable < ProyectoPP.Models.DocumentacionModel >

@{
    Layout = null;
}

<!DOCTYPE html> 

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @using (Html.BeginForm("Index", "Documentacion", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="postedFile" />
        <input type="submit" id="btnUpload" value="Upload" />
    }
    <hr />

    <table cellpadding="0" cellspacing="0">
        <tr>
            <th style="width:50px">File ID</th>
            <th style="width:120px">File Name</th>
            <th style="width:80px">Download</th>
        </tr>
            
        @foreach (var file in Model)
        {
            <tr>
                <td>@file.Id</td>
                <td>@file.Nombre</td>
                <td>
                    @using (Html.BeginForm("DownloadFile", "Documentacion", FormMethod.Post))
                    {
                        <input type="hidden" id="hfFileId" name="FileId" value="@file.Id"/>
                        <input type="submit" value="Descargar" class="btn btn-default" />
                    }
                </td>
            </tr>
        }
    </table>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript">
        function DownloadFile(fileId) {
            $("#hfFileId").val(fileId);
            $("#btnDownload")[0].click();
        };
    </script>
    
</body>
</html>