ProyectoPP/ProyectoPP/Controllers/proyectoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoPP.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace ProyectoPP.Controllers
{
    public class proyectoController : Controller
    {
        private patopurificEntitiesGeneral db = new patopurificEntitiesGeneral();
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return UserManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // Carga la intefaz de Index del módulo de proyecto
        // GET: proyecto
        public ActionResult Index()
        {
            
            if (System.Web.HttpContext.Current.User.IsInRole("Estudiante")) // Si el usuario es estudiante
            {

                var idproyecto = db.persona.Where(m => m.cedula == System.Web.HttpContext.Current.User.Identity.Name).First().IdProyecto;
                ViewBag.NombreProyecto = db.proyecto.Where(m => m.id == idproyecto).First().nombre;
                var proyecto = db.proyecto.Where(p => p.id == idproyecto);
                return View(proyecto.ToList());
            }
            var proyectos = db.proyecto.Include(p => p.persona);

            return View(proyectos.ToList());
        }


        // Carga la intefaz de Details del módulo de proyecto
        // GET: proyecto/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            proyecto proyecto = db.proyecto.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }

            ViewBag.Grupo = new SelectList(db.persona.Where(x => x.IdProyecto == id && x.cedula != proyecto.lider), "cedula", "nombre");
            return View(proyecto);
        }

        // Carga la intefaz de Create del módulo de proyecto
        // GET: proyecto/Create
        public ActionResult Create()
        {

            ViewBag.lider = new SelectList(db.persona.Where(x=>x.IdProyecto == null), "cedula", "nombre");
            return View();
        }

        //Guarda el nuevo proyecto en la base de datos.
        // POST: proyecto/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(proyecto proyecto)
        {
            if (ModelState.IsValid)
            {

                proyecto.id = proyecto.nombre + proyecto.lider;

                var persona = db.persona.Find(proyecto.lider);
                persona.IdProyecto = proyecto.id;
                
                db.proyecto.Add(proyecto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.lider = new SelectList(db.persona.Where(x => x.IdProyecto == null), "cedula", "nombre");
            return View(proyecto);
        }

        //Guarda los cambios del proyecto en la base de datos.
        // GET: proyecto/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            proyecto proyecto = db.proyecto.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }
            ViewBag.Listalider = new SelectList(db.persona.Where(x => x.IdProyecto == id), "cedula", "nombre", proyecto.persona1);
            ViewBag.ListaAgregar = new SelectList(db.persona.Where(x => x.IdProyecto == null), "cedula", "nombre");
            ViewBag.ListaQuitar = new SelectList(db.persona.Where(x => x.IdProyecto == id && x.cedula != proyecto.lider), "cedula", "nombre");
            return View(proyecto);
        }

        // POST: proyecto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                if (proyecto.listaAgregar != null) // Reviso si la lista es null para evitar errores
                {
                    for (int a = 0; a < proyecto.listaAgregar.Length; a++) // para cada elemento de la lista
                    {
                        // le asigno el proyecto a la persona
                        persona persona = db.persona.Find(proyecto.listaAgregar[a]);
                        persona.IdProyecto = proyecto.id;
                    }
                }

                if (proyecto.listaQuitar != null) // reviso si la lista es null para evitar errores
                {

                    for (int a = 0; a < proyecto.listaQuitar.Length; a++) // para cada elemento de la lista
                    {
                        // le quito el proyecto a la persona
                        persona persona = db.persona.Find(proyecto.listaQuitar[a]);
                        persona.IdProyecto = null;
                    }
                }

                db.Entry(proyecto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = proyecto.id});
            }
            ViewBag.lider = new SelectList(db.persona, "cedula", "nombre", proyecto.lider);
            return View(proyecto);
        }

        // Carga de interfaz de Delete del módulo de proyecto.
        // GET: proyecto/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            proyecto proyecto = db.proyecto.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }
            return View(proyecto);
        }

        // Borra de la base de datos el proyecto que se seleccionó.
        // POST: proyecto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            proyecto proyecto = db.proyecto.Find(id);
            db.proyecto.Remove(proyecto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoPP/ProyectoPP/Views/proyecto/Create.cshtml
@model ProyectoPP.Models.proyecto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Insertar nuevo Proyecto</h2>

@section Scripts {
    <!--Todo esto es para el date picker-->
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    
    <script type="text/javascript">

                             $(document).ready(function () {
                                 $('input[type=datetime]').datepicker({
                                     dateFormat: "yy-mm-dd",
                                     changeMonth: true,
                                     changeYear: true,
                                     yearRange: "-60:+0"
                                 });

                             });
   </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
   
            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "form-control", placeholder = "Fecha de Inicio" } })
                @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control", placeholder = "Fecha de Término" } })
                @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lider, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("lider", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.lider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{

                    IList<SelectListItem> listaEstados = new List<SelectListItem>
                        {
                        new SelectListItem{Text = "Pendiente", Value = "Pendiente"},
                        new SelectListItem{Text = "En Progreso", Value = "En Progreso"}
                        };
                    }
                    
                    @Html.DropDownListFor(model => model.estado, listaEstados, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <br>
        <br>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-default" />
                <button class="btn btn-default" onclick="location.href='@Url.Action("Create", "proyecto")';return false;">Cancelar</button>
            </div>
        </div>
    </div>
}

ProyectoPP/ProyectoPP/Views/proyecto/Delete.cshtml
@model ProyectoPP.Models.proyecto

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Proyecto</h2>

<h3>Está seguro que desa eliminar este proyecto?</h3>
<br>
<div>
    
    <dl class="dl-horizontal">

        <dt>
            <!-- Etiqueta para el nombre del proyecto que se ba a borrar -->
            <label for="Nombre">Nombre</label>
        </dt>
        <dd><!-- Nombre del proyecto que se ba a borrar -->
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <br />

        <dt>
            <!-- Etiqueta para la descripción del proyecto que se ba a borrar -->
            <label for="Descripcion">Descripción</label>
        </dt>
        <dd>
            <!-- Descripción del proyecto que se ba a borrar -->
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <br />
        <dt>
            <!-- Etiqueta para la fecha de inicio del proyecto que se ba a borrar -->
            <label for="FechaInicio">Fecha de inicio</label>
        </dt>
        <dd>
            
            <!-- Fecha de inicio del proyecto que se ba a borrar -->
            <text>@Model.fechaInicio.ToShortDateString()</text>
        </dd>

        <br />

        <dt>
            <!-- Etiqueta para lafecha de finlacización del proyecto que se ba a borrar -->
            <label for="FechaFinal">Fecha final</label>
        </dt>
        <dd>
            <!-- Fecha de finlacización del proyecto que se ba a borrar -->
            @Html.DisplayFor(model => model.fechaFinal)
        </dd>

        <br />

        <dt>
            <!-- Etiqueta para el nombre del lider del proyecto que se ba a borrar -->
            <label for="lider">Lider</label>
        </dt>
        <dd>
            <!-- Nombre del lider del proyecto que se ba a borrar -->
            @Html.DisplayFor(model => model.persona1.nombre)
        </dd>
        <br>

        <dt>
            <!-- Etiqueta para el estado del proyecto que se ba a borrar -->
            <label for="estado">Estado</label>
        </dt>
        <dd>
            <!-- Estado del proyecto que se ba a borrar -->
            @Html.DisplayFor(model => model.estado)
        </dd>

        <br>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-default" />
                <button class="btn btn-default" onclick="location.href='@Url.Action("Details", "proyecto", new { id = Model.id })';return false;">Cancelar</button>
            </div>
        </div>
    }

    <br>

</div>

ProyectoPP/ProyectoPP/Views/proyecto/Details.cshtml
@model ProyectoPP.Models.proyecto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles de Proyecto</h2>

<div>

    <h4>Nombre del Proyecto: @Html.DisplayFor(model => model.nombre)</h4>
        
    <div class="form-group">
        <div class="col-md-offset-6 col-md-10">
            <!--Estos botones funcionan como los action links. Solo que el orden de los parametros es un poco distinto en el orden-->
            <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "proyecto", new { id = Model.id })'">Editar</button>
            <button class="btn btn-default" onclick="location.href='@Url.Action("Delete", "proyecto", new { id = Model.id })'">Eliminar</button>
        </div>
    </div>

    <dl class="dl-horizontal">

        <dt>
            <label for="Nombre">Nombre</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <br/>

        <dt>
            <label for="Descripcion">Descripción</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <br/>
        
        <dt>
            <label for="FechaInicio">Fecha de inicio</label>
        </dt>
        <dd>
            <text>@Model.fechaInicio.ToShortDateString() </text>
        </dd>

        <br />

        <dt>
            <label for="FechaFinal">Fecha final</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fechaFinal)
        </dd>

        <br />

        <dt>
            <label for="lider">Lider</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.persona1.nombre)
        </dd>

        <br>

        <dt>
            <label for="estado">Estado</label>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <br>

        <dt>
            <label for="Grupo">Grupo de Trabajo</label>
        </dt>
        <dd>
            @Html.ListBox("Grupo de Trabajo", (MultiSelectList)ViewBag.Grupo, htmlAttributes: new { @class = "form-control", @readOnly = true })
        </dd>
                 

        <br />

    </dl>
</div>

ProyectoPP/ProyectoPP/Views/proyecto/Edit.cshtml
@model ProyectoPP.Models.proyecto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Detalles</h2>

@section Scripts {
    <!--Todo esto es para el date picker-->
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">

    <script type="text/javascript">

                             $(document).ready(function () {
                                 $('input[type=datetime]').datepicker({
                                     dateFormat: "yy-mm-dd",
                                     changeMonth: true,
                                     changeYear: true,
                                     yearRange: "-60:+0"
                                 });

                             });
    </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nombre del Proyecto: @Html.DisplayFor(model => model.nombre)</h4>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
           @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @class = "form-control"}})
                @Html.ValidationMessageFor(model => model.fechaInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lider, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.lider, (SelectList)ViewBag.Listalider, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.lider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @{

                    IList<SelectListItem> listaEstados = new List<SelectListItem>
                        {
                        new SelectListItem{Text = "Pendiente", Value = "Pendiente"},
                        new SelectListItem{Text = "En Progreso", Value = "En Progreso"},
                        new SelectListItem{Text = "Cancelado", Value = "Cancelado"},
                        new SelectListItem{Text = "Completado", Value = "Completado"}
                        };
                }

                @Html.DropDownListFor(m => m.estado, listaEstados, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.Label("Agregar Miembros:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m=> m.listaAgregar, (MultiSelectList)ViewBag.ListaAgregar, htmlAttributes: new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.lider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Quitar Miembros:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m=> m.listaQuitar, (MultiSelectList)ViewBag.ListaQuitar, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.lider, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Aceptar" class="btn btn-default" />
            <button class="btn btn-default" onclick="location.href='@Url.Action("Edit", "proyecto", new { id = Model.id })';return false;">Cancelar</button>
        </div>
    </div>

}

ProyectoPP/ProyectoPP/Views/proyecto/Index.cshtml
@model IEnumerable<ProyectoPP.Models.proyecto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listado de Proyectos</h2>

<br>

<div class="form-group">
    
    @if (true)
    {
        string resp = Html.Action("EsEstudiante", "Roles").ToString();
        if (resp == "1")
        {
            <h4>@ViewBag.NombreProyecto </h4>
        }
        else
        {
            <div class="col-md-offset-10 col-md-10">
                <button class="btn btn-default" onclick="location.href='@Url.Action("Create", "proyecto",new { })'">Insertar Proyecto</button>
            </div>
        }

    }

</div>



<br /><br /><br /><br />

<table class="table">

    <tbody style="background-image:url(pato4.jpg); background-repeat:no-repeat">
        <!--Etiquetas de los atriutos importantes que se utilizaran -->
        <tr>
            <th>
                <label>Nombre</label>
            </th>
            <th>
                <label>Descripcion</label>
            </th>
            <th>
                <label>Fecha de Inicio</label>
            </th>
            <th>
                <label>Fecha de Término</label>
            </th>
            <th>
                <label>Lider</label>
            </th>
            <th></th>
        </tr>

        <!-- Muestra la información de las tuplas de la base de dartos -->
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    <text>@item.fechaInicio.ToShortDateString()</text>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaFinal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.persona1.nombre)
                </td>
                <td>
                    @Html.ActionLink("Detalles", "Details", new { id = item.id })

                </td>
            </tr>
            }
    </tbody>
</table>